### PR TITLE
fix: race condition in test

### LINKED ISSUE #36: Fix flagged race conditions
Including the `-race` flag in the execution of the tests throws errors due to discovered race conditions. Fix these and include `-race` flag in the `make test` command.

### PR DESCRIPTION
**Pull request by skyerus**
## This PR

Fixes a race condition in a test and runs tests with the race flag by default

### Related Issues

Fixes #36

### CODE REVIEW

File: hooks/open-telemetry/pkg/otel_test.go [hunk 1]
```diff
@@ -129,20 +128,21 @@ func TestOtelHookMethods(t *testing.T) {
...
 		}
 
 		// unlock the resource and ensure that the previously blocked goroutine can now complete
 		otelHook.Finally(openfeature.HookContext{}, openfeature.HookHints{})
 
-		// account for slow execution time to ensure that goroutine is no longer blocked
-		// (cannot use the .Wait method in this example) as the after method has not yet been called for the blocked goroutine
-		time.Sleep(500 * time.Millisecond)
-		if blocked {
+		ticker := time.NewTicker(500 * time.Millisecond)
```
Comment (james-milligan) [inline hooks/open-telemetry/pkg/otel_test.go:142]: Is this cleaner than using `time.After`?

Comment (skyerus) [reply hooks/open-telemetry/pkg/otel_test.go]: thanks, done

**Review by james-milligan — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]
