### PR TITLE
fix: nil client causes panic

### LINKED ISSUE #407: [bug] Panic in flagd provider
The flagd provider sometimes panics on startup. This is because[ the client is `nil` until init is called](https://github.com/open-feature/go-sdk-contrib/blob/febd9b89878f2a998df39698e752dd3583ffd56e/providers/flagd/pkg/service/rpc/service.go#L77), which happens in a new goroutine and therefore is sometimes not ready.

Related to: https://github.com/open-feature/go-sdk/issues/238

### PR DESCRIPTION
**Pull request by thisthat**
## This PR

- fixes #407 

related to: https://github.com/open-feature/go-sdk/issues/238

### CODE REVIEW

File: providers/flagd/pkg/provider.go [hunk 1]
```diff
@@ -158,6 +161,12 @@ func (p *Provider) ObjectEvaluation(
 	return p.service.ResolveObject(ctx, flagKey, defaultValue, evalCtx)
 }
 
+func (p *Provider) setStatus(status of.State) {
+	p.mtx.Lock()
+	defer p.mtx.Unlock()
+	p.status = status
```
Comment (toddbaert) [inline providers/flagd/pkg/provider.go:167]: I would assume this is atomic and therefore locking doesn't help? :thinking:

Comment (toddbaert) [reply providers/flagd/pkg/provider.go:167]: Though I think you want to make sure this can run DURING init.

I think I thread isn't blocked by a lock it already owns, right? So I guess you might want to lock in init() and well as here.

Comment (bacherfl) [reply providers/flagd/pkg/provider.go:167]: I think we do need it, yes - if you execute the tests with the `-race` flag enabled, a data race error occurs, due to `p.status` being set in the goroutine created within the `Init()` function, while being accessed via the `Status()` function in the test

**Review by toddbaert — APPROVED** [review]

**Comment by toddbaert** [comment]
Thanks @bacherfl and @thisthat !
