### PR TITLE
fix(flagd): do not retry for certain status codes (#756)

### LINKED ISSUE #756: Infinite retry to establish connection to FlagSyncService in Flagd golang provider
Golang Flagd provider tries to establish connection to FlagSyncService in an infinite loop. The retry at the this point happens on any error. This is unwanted as the connection can fail due to permission issues and shouldn't be retired infinitely.

### PR DESCRIPTION
**Pull request by alexandraoberaigner**
# This PR

This pull request introduces configurable **retry and fatal error handling** for the **in-process gRPC sync provider** in the `flagd` project. The main changes include adding new configuration options for retry backoff timing and fatal status codes, refactoring environment variable parsing, and updating service initialization and error handling logic. 

## Related Issues

- Reopens the changes from #783
- Fixes #756

### Retry and fatal error configuration (most important):

* Added new configuration options (`RetryBackoffMs`, `RetryBackoffMaxMs`, `FatalStatusCodes`) to `ProviderConfiguration`, with environment variable support and helper functions for parsing integer values from environment variables. [[1]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17R29-R31) [[2]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17R51-R53) [[3]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17R75-R77) [[4]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17R92-R94) [[5]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17L230-R249) [[6]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17R428-R449)
* Updated provider and service initialization to pass the new retry and fatal error configuration fields, enabling customization of retry timing and fatal error handling for sync streams. [[1]](diffhunk://#diff-976dda135f2019e49fc8d97d64cd4935fbab8851d7f6eba61307bf485c6e3244R77-R79) [[2]](diffhunk://#diff-4bbb263d6d2f61a7d857cda69528bb929b36db6b4a9e98c4a7666e389f7f9ad5R115-R117) [[3]](diffhunk://#diff-4bbb263d6d2f61a7d857cda69528bb929b36db6b4a9e98c4a7666e389f7f9ad5R575-R578)

### Refactoring and code quality:

* Refactored environment variable parsing for integer values using a new helper function, simplifying and unifying logic for multiple configuration fields. [[1]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17L162-R175) [[2]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17L188-R192) [[3]](diffhunk://#diff-0c3afbb3c6a8f6a417d9decdf99f1dfad30fcbd445029868fbca1a2b68a4cc17L230-R249)
* Moved gRPC retry policy construction and fatal status code normalization to a new file `grpc_config.go`, making the code more modular and testable. [[1]](diffhunk://#diff-431e1694cab09598ed0a65d71eb6f14d0352c3a208ed215ce03f01711bdde2b8R1-R67) [[2]](diffhunk://#diff-bfa65fc1a13250019228c916bf3b306b9f5753921dae55486117948f1bdce6a6R15-L59) [[3]](diffhunk://#diff-bfa65fc1a13250019228c916bf3b306b9f5753921dae55486117948f1bdce6a6R41-R44) [[4]](diffhunk://#diff-bfa65fc1a13250019228c916bf3b306b9f5753921dae55486117948f1bdce6a6R59) [[5]](diffhunk://#diff-bfa65fc1a13250019228c916bf3b306b9f5753921dae55486117948f1bdce6a6L158-R129)

### Error handling improvements:

* Enhanced sync error handling to detect fatal gRPC status codes and transition the provider to a fatal state, preventing endless retries on unrecoverable errors.
* Updated test coverage for retry policy construction, fatal status code normalization, and camel-case conversion logic in `grpc_config_test.go`.

### CODE REVIEW

File: tests/flagd/testframework/utils.go [hunk 1]
```diff
@@ -78,6 +78,9 @@ func (vc *ValueConverter) ConvertToReflectValue(valueType, value string, fieldTy
 			panic(fmt.Errorf("failed to convert %s to long: %w", value, err))
 		}
 		return reflect.ValueOf(longVal).Convert(fieldType)
+	case "StringList":
+		arrayVal := strings.Split(value, ",")
```
[the remark this answers is not in the document]
Comment (alexandraoberaigner) [reply tests/flagd/testframework/utils.go]: yes, good catch! will update this & add a test

File: providers/flagd/pkg/service/in_process/grpc_sync.go [hunk 2]
```diff
@@ -193,6 +160,8 @@ func (g *Sync) IsReady() bool {
 func (g *Sync) Sync(ctx context.Context, dataSync chan<- sync.DataSync) error {
 	g.Logger.Info("starting continuous flag synchronization")
 
+	time.Sleep(500 * time.Millisecond)
```
Comment (guidobrei) [inline providers/flagd/pkg/service/in_process/grpc_sync.go]: Is this a debug leftover?

File: providers/flagd/pkg/service/in_process/grpc_sync.go [hunk 3]
```diff
@@ -248,12 +233,6 @@ func (g *Sync) performSyncCycle(ctx context.Context, dataSync chan<- sync.DataSy
 
 // handleFlagSync processes messages from the sync stream with proper context handling
 func (g *Sync) handleFlagSync(ctx context.Context, stream syncv1grpc.FlagSyncService_SyncFlagsClient, dataSync chan<- sync.DataSync) error {
-	// Mark as ready on first successful stream
-	g.initializer.Do(func() {
-		g.ready = true
-		g.Logger.Info("sync service is now ready")
-	})
```
Comment (alexandraoberaigner) [inline providers/flagd/pkg/service/in_process/grpc_sync.go]: Note: This moved to lines 275-279 to set ready = true only after the first stream cycle was successful not during the cycle.

File: providers/flagd/pkg/service/in_process/grpc_sync.go [hunk 4]
```diff
@@ -207,12 +176,31 @@ func (g *Sync) Sync(ctx context.Context, dataSync chan<- sync.DataSync) error {
...
+					g.Logger.Error(errStr)
+					return &of.ProviderInitError{
+						ErrorCode: of.ProviderFatalCode,
+						Message:   errStr,
+					}
+				}
+			}
+
+			// Backoff before retrying
+			time.Sleep(time.Duration(g.RetryBackOffMs) * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (alexandraoberaigner) [reply providers/flagd/pkg/service/in_process/grpc_sync.go]: I'm reluctant to put this change in a separate PR since Todd's idea was to unify implementations (Java and Go) as feedback on the initial PR -> see [comment here](https://github.com/open-feature/go-sdk-contrib/pull/783#pullrequestreview-3377852604)

File: providers/flagd/pkg/service/in_process/grpc_sync.go [hunk 5]
```diff
@@ -207,12 +172,32 @@ func (g *Sync) Sync(ctx context.Context, dataSync chan<- sync.DataSync) error {
...
+						return &of.ProviderInitError{
+							ErrorCode: of.ProviderFatalCode,
+							Message:   errStr,
+						}
+					}
+				}
+			}
+
+			// Backoff before retrying
+			time.Sleep(time.Duration(g.RetryBackOffMaxMs) * time.Millisecond)
```
Comment (aepfli) [inline providers/flagd/pkg/service/in_process/grpc_sync.go]: I am not a big fan of our blocking sleeps, as they clearly have some disadvantages, should we maybe stick to a timer for this kind of logic? like 
```golang
select {
case <-time.After(time.Duration(g.RetryBackOffMaxMs) * time.Millisecond):
    // ... code here ...
case <-ctx.Done():
    return // Allows cancellation
}
```

Comment (toddbaert) [reply providers/flagd/pkg/service/in_process/grpc_sync.go]: There's disadvantages of sleep, but I think right now this is better than nothing, because nothing == a tight loop in some cases that is a serious bug in some situations.

**Review by toddbaert — COMMENTED** [review]
This implementation looks good to me, nice work overall. One thing I think we need in addition is that we should use the same FATAL codes in RPC mode - so I think you will have to add something similar to what you have done in `pkg/service/rpc/service.go`... do you agree? Since both modes have streams, I think it makes sense for both streams to use this rule.

With respect to @aepfli and @guidobrei 's comment about separating things... I can go either way, but you will need 1 more approval besides mine and I think it might make it easier for you to debug the e2e CI failure.

**Comment by alexandraoberaigner** [comment]
[Q] does someone have an idea why the gherkin tests for SYNC_PORT still fail even though I excluded them with ~@sync-port

**Review by guidobrei — APPROVED** [review]
LGTM ❤️
